apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    backstage.io/managed-by-location: url:https://github.com/damodarkumar/github-actions-terraform/blob/main/terraform/catalog-info.yaml 
  name: terraform-project
spec:
  type: service
  lifecycle: production
  owner: platform-engineering-team
  provides:
    - type: GitHubAction
      targets:
        - damodarkumar/github-actions-terraform  # Replace with your GitHub repository in the format "owner/repo"
      implementsApis:
        - apiVersion: backstage.io/v1alpha1
          kind: GitHubAction
          name: invoke-terraform
          schema:
            url: https://github.com/damodarkumar/github-actions-terraform/blob/main/skeleton/.github/workflows/provision_ec2.yaml  # Replace with the actual URL of your workflow file
            method: post

