apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-app
  description: My awesome app
spec:
  type: github-actions
  lifecycle: production
  template: github-actions
  owner: damodarkumar
  repository: github-actions-terraform
