name: Invoke Terraform Worfklow

on:
  workflow_dispatch:
    inputs:
      ec2-name:
        description: "EC2 name"
        required: false
        default: ""
        type: "string"

      ec2-type:
        description: "EC2 type"
        required: false
        default: ""
        type: "choice"
        options: 
        - t3.micro
        - t2.micro
        
        

      provider-region:
        description: "provider region"
        required: false
        default: ""
        type: "choice"
        options: 
        - eu-north-1
        - eu-east-1
        
        
jobs:
  invoke-terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: '${{ secrets.TF_USER_AWS_KEY }}'
          aws-secret-access-key: '${{ secrets.TF_USER_AWS_SECRET }}'
          aws-region: eu-north-1
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      - name: Terraform Apply
        id:   apply
        env:
          TF_VAR_ec2_name:  "${{ github.event.inputs.ec2-name }}"
          TF_VAR_ec2_type:  "${{ github.event.inputs.ec2-type }}"
          TF_VAR_provider_region:  "${{ github.event.inputs.provider-region }}"
        run: |
          cd terraform/
          terraform init
          terraform validate
          terraform plan 
          terraform apply -auto-approve
     
